DROP TABLE IF EXISTS item;

CREATE TABLE item (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_by VARCHAR(255),
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255),
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INTEGER DEFAULT 0 NOT NULL,
  item_name VARCHAR(250) NOT NULL,
  item_description VARCHAR(250) NOT NULL,
  item_status VARCHAR(250) NOT NULL,
  ITEM_AVAILABLE_COUNT BIGINT,
  item_amount BIGINT
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_by VARCHAR(255) DEFAULT 'ADMIN',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255) DEFAULT 'ADMIN',
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INTEGER DEFAULT 0 NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS cart;

CREATE TABLE cart (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_by VARCHAR(255) DEFAULT 'ADMIN',
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL,
  LAST_MODIFIED_BY VARCHAR(255) DEFAULT 'ADMIN',
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INTEGER DEFAULT 0 NOT NULL,
  cart_status VARCHAR(250) DEFAULT 'NOT_PURCHASED' NOT NULL,
  cart_amount VARCHAR(250) DEFAULT 0 NOT NULL,
  USER_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS cart_item;

CREATE TABLE cart_item (
  CART_ID BIGINT NOT NULL,
  ITEM_ID BIGINT NOT NULL
);